# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a076c53c658957d8cca1b1ad83f6216ad86910a37ba1f537ba4a845867a7da37e781c81dbffaf090db63aa82e26ea4a97321692d4b66175faf0284edc23767e

test:
  secret_key_base: 18fd6f83cb4e351cdba6b30ef65a26d3abc94655958de4aa078daa15f14282ed9f335202832a3442a714f924d35e8c073041059ecee89c404df9596b29bd4291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
